// <auto-generated />
using System;
using GestionBoutiqueC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionBoutiqueWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241113231534_Fixtures")]
    partial class Fixtures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionBoutiqueC.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtatArticle")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.Property<double>("QteStock")
                        .HasColumnType("float");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 11, 13, 23, 15, 33, 49, DateTimeKind.Local).AddTicks(8612),
                            EtatArticle = 0,
                            Libelle = "Bonbon Jina",
                            Prix = 100,
                            QteStock = 50.0,
                            Reference = "A00001",
                            UpdateAt = new DateTime(2024, 11, 13, 23, 15, 33, 49, DateTimeKind.Local).AddTicks(8614)
                        });
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surnom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Rue de Paris",
                            CreateAt = new DateTime(2024, 11, 13, 23, 15, 33, 44, DateTimeKind.Local).AddTicks(3654),
                            Surnom = "kiki",
                            Telephone = "774799479",
                            UpdateAt = new DateTime(2024, 11, 13, 23, 15, 33, 44, DateTimeKind.Local).AddTicks(4640),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetteId")
                        .HasColumnType("int");

                    b.Property<double>("QteDette")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DetteId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreateAt = new DateTime(2024, 11, 13, 23, 15, 33, 49, DateTimeKind.Local).AddTicks(607),
                            DetteId = 1,
                            QteDette = 5.0,
                            UpdateAt = new DateTime(2024, 11, 13, 23, 15, 33, 49, DateTimeKind.Local).AddTicks(608)
                        });
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Dette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtatDette")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.Property<double>("MontantRestant")
                        .HasColumnType("float");

                    b.Property<double>("MontantVerse")
                        .HasColumnType("float");

                    b.Property<int>("TypeDette")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Dettes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreateAt = new DateTime(2024, 11, 13, 23, 15, 33, 48, DateTimeKind.Local).AddTicks(3249),
                            Date = new DateTime(2024, 10, 13, 23, 15, 33, 48, DateTimeKind.Local).AddTicks(3846),
                            EtatDette = 0,
                            Montant = 500.0,
                            MontantRestant = 300.0,
                            MontantVerse = 200.0,
                            TypeDette = 0,
                            UpdateAt = new DateTime(2024, 11, 13, 23, 15, 33, 48, DateTimeKind.Local).AddTicks(3255)
                        });
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetteId")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DetteId");

                    b.ToTable("Paiements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 11, 13, 23, 15, 33, 54, DateTimeKind.Local).AddTicks(3412),
                            Date = new DateTime(2024, 11, 13, 23, 15, 33, 54, DateTimeKind.Local).AddTicks(5247),
                            DetteId = 1,
                            Montant = 200.0,
                            UpdateAt = new DateTime(2024, 11, 13, 23, 15, 33, 54, DateTimeKind.Local).AddTicks(3418)
                        });
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            ClientId = 1,
                            CreateAt = new DateTime(2024, 11, 13, 23, 15, 33, 47, DateTimeKind.Local).AddTicks(2099),
                            Email = "admin@example.com",
                            Login = "admin",
                            Password = "admin",
                            UpdateAt = new DateTime(2024, 11, 13, 23, 15, 33, 47, DateTimeKind.Local).AddTicks(2105),
                            UserRole = 1
                        });
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Client", b =>
                {
                    b.HasOne("GestionBoutiqueC.Entities.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("GestionBoutiqueC.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Detail", b =>
                {
                    b.HasOne("GestionBoutiqueC.Entities.Article", "Article")
                        .WithMany("Details")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionBoutiqueC.Entities.Dette", "Dette")
                        .WithMany("Details")
                        .HasForeignKey("DetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Dette");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Dette", b =>
                {
                    b.HasOne("GestionBoutiqueC.Entities.Client", "Client")
                        .WithMany("Dettes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Paiement", b =>
                {
                    b.HasOne("GestionBoutiqueC.Entities.Dette", "Dette")
                        .WithMany("Paiements")
                        .HasForeignKey("DetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dette");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Article", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Client", b =>
                {
                    b.Navigation("Dettes");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.Dette", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("GestionBoutiqueC.Entities.User", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
